2015 December
-------------
49  1 Tue 9:30 (1:30 flex)
    2 Wed 8
    3 Thu 8
    4 Fri 8
    5 Sat
    6 Sun
50  7 Mon 8
    8 Tue 8
    9 Wed 8
   10 Thu 8 (8 VAB)
   11 Fri 8
   12 Sat
   13 Sun
51 14 Mon 8
   15 Tue 8
   16 Wed 8
   17 Thu 8
   18 Fri 8
   19 Sat
   20 Sun
52 21 Mon 8
   22 Tue 8
   23 Wed 8
   24 Thu 8
   25 Fri 8
   26 Sat
   27 Sun
53 28 Mon 8 (8 semester)
   29 Tue 8 (8 semester)
   30 Wed 8 (8 semester)
   31 Thu 8
