2015 November
-------------
44  1 Sun
45  2 Mon   semester
    3 Tue   semester
    4 Wed   semester
    5 Thu   semester
    6 Fri   semester
    7 Sat
    8 Sun
46  9 Mon 6 (-2 flex)
   10 Tue 8
   11 Wed 8
   12 Thu 10 (2 flex)
   13 Fri 8
   14 Sat
   15 Sun
47 16 Mon 8
   17 Tue 8
   18 Wed 8
   19 Thu 8
   20 Fri 8
   21 Sat
   22 Sun
48 23 Mon 8
   24 Tue 8
   25 Wed 8
   26 Thu 8
   27 Fri 8
   28 Sat
   29 Sun
49 30 Mon 8
