2015 July
---------
27  1 Wed 8
    2 Thu 8
    3 Fri 8
    4 Sat
    5 Sun
28  6 Mon 8 (8 semester)
    7 Tue 8 (8 semester)
    8 Wed 8 (8 semester)
    9 Thu 8 (8 semester)
   10 Fri 8 (8 semester)
   11 Sat
   12 Sun
29 13 Mon 8 (8 semester)
   14 Tue 8 (8 semester)
   15 Wed 8 (8 semester)
   16 Thu 8 (8 semester)
   17 Fri 8 (8 semester)
   18 Sat
   19 Sun
30 20 Mon 8 (8 semester)
   21 Tue 8 (8 semester)
   22 Wed 8 (8 semester)
   23 Thu 8 (8 semester)
   24 Fri 8 (8 semester)
   25 Sat
   26 Sun
31 27 Mon 8
   28 Tue 8
   29 Wed 8
   30 Thu 8
   31 Fri 8
