2015 November
-------------
44  1 Sun
45  2 Mon 8 (8 semester)
    3 Tue 8 (8 semester)
    4 Wed 8 (8 semester)
    5 Thu 8 (8 semester)
    6 Fri 8 (8 semester)
    7 Sat
    8 Sun
46  9 Mon 6 (-2 flex)
   10 Tue 8
   11 Wed 8
   12 Thu 10 (2 flex)
   13 Fri 8
   14 Sat
   15 Sun
47 16 Mon 8
   17 Tue 8
   18 Wed 8
   19 Thu 8
   20 Fri 8
   21 Sat
   22 Sun
48 23 Mon 8
   24 Tue 8
   25 Wed 8
   26 Thu 8
   27 Fri 7 (-1 flex)
   28 Sat
   29 Sun
49 30 Mon 8
