2016 January
------------
53  1 Fri
    2 Sat
    3 Sun
01  4 Mon 7 (-1 flex)
    5 Tue 6 (+2 flex)
    6 Wed 8
    7 Thu 8
    8 Fri 8
    9 Sat
   10 Sun
02 11 Mon 8
   12 Tue 8
   13 Wed 8
   14 Thu 6 (-2 flex)
   15 Fri   sjuk
   16 Sat
   17 Sun
03 18 Mon 6 (-2 flex)
   19 Tue 8
   20 Wed 8
   21 Thu 8
   22 Fri 8
   23 Sat
   24 Sun
04 25 Mon 8
   26 Tue 8
   27 Wed 8
   28 Thu 8
   29 Fri 8
   30 Sat
   31 Sun
