2016 April
----------
13  1 Fri 8
    2 Sat
    3 Sun
14  4 Mon 9 (+1 flex)
    5 Tue 8
    6 Wed 8
    7 Thu 8
    8 Fri 8
    9 Sat
   10 Sun
15 11 Mon 8
   12 Tue 7:30 (-0:30 flex)
   13 Wed 7 (-1 flex) strömavbrott
   14 Thu 8
   15 Fri 8
   16 Sat
   17 Sun
16 18 Mon 8
   19 Tue 8
   20 Wed 8
   21 Thu 8
   22 Fri 8
   23 Sat
   24 Sun
17 25 Mon 8
   26 Tue 8
   27 Wed 8
   28 Thu 8
   29 Fri 8
   30 Sat
