2016 March
----------
09  1 Tue 9 (+1 flex)
    2 Wed 8
    3 Thu 8
    4 Fri 8
    5 Sat
    6 Sun
10  7 Mon 8
    8 Tue 7 (-1 flex) bankärende
    9 Wed 8
   10 Thu 8
   11 Fri 8
   12 Sat
   13 Sun
11 14 Mon 8:30 (+0:30 flex)
   15 Tue 8
   16 Wed 8
   17 Thu 8
   18 Fri 8
   19 Sat
   20 Sun
12 21 Mon 8
   22 Tue 8
   23 Wed 8
   24 Thu 8 (+4 flex)
   25 Fri 
   26 Sat
   27 Sun
13 28 Mon 
   29 Tue 8
   30 Wed 8
   31 Thu 8
