1970 January
------------
01  1 Thu 7 (-1 flex)
    2 Fri 9 (1 flex)
    3 Sat 0:30 (0:30 flex)
    4 Sun
02  5 Mon 8:30
    6 Tue 7:30
    7 Wed 8
    8 Thu 8
    9 Fri 8 (4:30 VAB)
   10 Sat
   11 Sun
03 12 Mon 8
   13 Tue 8
   14 Wed 8 This was a fun day!
   15 Thu 8
   16 Fri 8
   17 Sat
   18 Sun
04 19 Mon 8 (8 vacation)
   20 Tue 8 (8 vacation)
   21 Wed 8
   22 Thu 8
   23 Fri 8
   24 Sat
   25 Sun
05 26 Mon 8
   27 Tue 8
   28 Wed 8
   29 Thu 8
   30 Fri 7:15 (-0:45 flex)
   31 Sat
